{
 "title": "Мониторим курс батов",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "THB изменение за день, %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT daily_change_pct\r\nFROM finance_marts.dm_weekly_report \r\nWHERE char_code = 'THB' \r\nORDER BY requested_date DESC \r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Курс USD/THB/EUR",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT \r\n  char_code AS \"Валюта\", \r\n  rate AS \"Текущий курс\", \r\n  prev_date_rate AS \"Предыдущий день\",\r\n  avg_rate_7d AS \"Среднее за 7 дней\"\r\nFROM finance_marts.dm_weekly_report\r\nWHERE char_code in ('USD', 'EUR', 'THB')\r\nORDER BY requested_date DESC,\r\n  CASE\r\n    WHEN char_code = 'THB' THEN 1\r\n\t  WHEN char_code = 'USD' THEN 2\r\n\t  ELSE 3\r\n  END\r\nLIMIT 3"
    }
   ]
  },
  {
   "title": "Динамика курса THB за месяц",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT requested_date::DATE, rate \r\nFROM finance_int.int_daily_rates\r\nWHERE char_code = 'THB' \r\n  AND requested_date >= NOW() - INTERVAL '30 days' \r\nORDER BY requested_date"
    }
   ]
  }
 ]
}