{
 "title": "Анализ нескольких валют",
 "description": "USD, EUR, EGP, THB, TRY и VND",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Тепловая карта изменения курса валют",
   "type": "table",
   "description": "В какие дни недели валюты чаще растут или падают (среднее за 90 дней)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT\r\n    char_code AS \"Валюта\",\r\n    CASE EXTRACT(dow FROM requested_date) \r\n      WHEN 0 THEN 'Вс'\r\n      WHEN 1 THEN 'Пн'\r\n      WHEN 2 THEN 'Вт'\r\n      WHEN 3 THEN 'Ср'\r\n      WHEN 4 THEN 'Чт'\r\n      WHEN 5 THEN 'Пт'\r\n      WHEN 6 THEN 'Сб'\r\n    END AS \"День недели\",\r\n    AVG(daily_change_pct) AS avg_change\r\nFROM finance_int.int_daily_rates\r\nWHERE requested_date >= NOW() - INTERVAL '90 days'\r\n  AND char_code IN ('USD', 'EUR', 'EGP', 'THB', 'TRY', 'VND')\r\nGROUP BY char_code, EXTRACT(dow FROM requested_date)\r\nORDER BY char_code,\r\n         CASE EXTRACT(dow FROM requested_date)\r\n         WHEN 0 THEN 7\r\n         ELSE EXTRACT(dow FROM requested_date)\r\n         END;"
    }
   ]
  },
  {
   "title": "Изменение курса за 30 дней, %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT char_code, requested_date::DATE, daily_change_pct \r\nFROM finance_int.int_daily_rates\r\nWHERE requested_date >= NOW() - INTERVAL '30 days' \r\n  AND char_code IN ('USD', 'EUR', 'EGP', 'THB', 'TRY', 'VND')"
    }
   ]
  },
  {
   "title": "Детальные данные",
   "type": "table",
   "description": " 7 последних дней",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT * FROM finance_marts.dm_weekly_report\r\nORDER BY requested_date DESC, char_code ASC"
    }
   ]
  }
 ]
}