{
 "title": "Анализ волатильности USD",
 "description": "Мониторим изменчивость курса USD",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "7-дневное скользящее среднее",
   "type": "timeseries",
   "description": "Общий тренд",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT requested_date, avg_rate_7d\r\nFROM finance_int.int_daily_rates \r\nWHERE char_code = 'USD' \r\n  --AND requested_date >= NOW() - INTERVAL '90' DAY\r\nORDER BY requested_date DESC "
    }
   ]
  },
  {
   "title": "Изменение курса, %",
   "type": "timeseries",
   "description": "Дни с резкими скачками",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT requested_date, daily_change_pct\r\nFROM finance_int.int_daily_rates\r\nWHERE char_code = 'USD'\r\n  --AND requested_date >= NOW() - INTERVAL '90' DAY\r\nORDER BY requested_date DESC "
    }
   ]
  },
  {
   "title": "Топ-5 дней по суточному изменению за квартал",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "currency_db",
     "rawSql": "SELECT\r\n  to_char(requested_date, 'dd.mm.yyyy') as \"Дата\", \r\n  CASE EXTRACT(dow FROM requested_date)\r\n   WHEN 0 THEN 'Вс'\r\n\t WHEN 1 THEN 'Пн'\r\n\t WHEN 2 THEN 'Вт'\r\n\t WHEN 3 THEN 'Ср'\r\n\t WHEN 4 THEN 'Чт'\r\n\t WHEN 5 THEN 'Пт'\r\n\t ELSE 'Сб'\r\n  END AS \"День недели\",\r\n  daily_change_pct \"Изменение, %\"\r\nFROM finance_int.int_daily_rates\r\nWHERE char_code = 'USD' \r\n  AND requested_date >= NOW() - INTERVAL '90' DAY\r\n  AND daily_change_pct IS NOT NULL\r\nORDER BY ABS(daily_change_pct) DESC, requested_date DESC\r\nLIMIT 5"
    }
   ]
  }
 ]
}