apiVersion: 1

datasources:
  - name: Currency Rates DB
    uid: currency_postgres
    type: postgres
    url: postgres:5432
    user: grafanareader
    secureJsonData:
      password: grafana_pass
    jsonData:
      database: currency_db
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
  - name: Airflow Metabase
    uid: airflow_postgres
    type: postgres
    url: postgres:5432
    user: airflowreader
    secureJsonData:
      password: afreader_pass
    jsonData:
      database: airflow
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false