services:
  postgres:
    image: postgres:15
    container_name: cur_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - currency_pgdata:/var/lib/postgresql/data
      - ./sql/init_airflow_db.sql:/docker-entrypoint-initdb.d/init_airflow_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5

  airflow-webserver:
    image: my-airflow-with-dbt
    container_name: cur_airflow_webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://${DB_USER}:${DB_PWD}@postgres/airflow
      DATABASE_URL: postgresql://${DB_USER}:${DB_PWD}@postgres/${DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__RBAC: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      # переменные для SMTP
      # перенастроено через Connections
      # AIRFLOW__SMTP__SMTP_HOST: smtp.yandex.ru
      # AIRFLOW__SMTP__SMTP_PORT: 465
      # AIRFLOW__SMTP__SMTP_SSL: True
      # AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      # AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PWD}
      # AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_USER}
      REPORT_MAIL_TO: ${MAIL_TO}
      # AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      # переменные для dbt
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PWD}
      DB_NAME: ${DB_NAME} 
    volumes:
      - ./src:/opt/airflow/src
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./currency_dbt:/opt/airflow/currency_dbt
      - ./airflow/reports:/opt/airflow/reports/
    command: >
      bash -c "cd /opt/airflow/currency_dbt && dbt deps &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver
      "
    restart: unless-stopped

  airflow-scheduler:
    image: my-airflow-with-dbt
    container_name: cur_airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://${DB_USER}:${DB_PWD}@postgres/airflow
      DATABASE_URL: postgresql://${DB_USER}:${DB_PWD}@postgres/${DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # переменные для SMTP
      # перенастроено через Connections
      # AIRFLOW__SMTP__SMTP_HOST: smtp.yandex.ru
      # AIRFLOW__SMTP__SMTP_PORT: 465
      # AIRFLOW__SMTP__SMTP_SSL: True
      # AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      # AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PWD}
      # AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_USER}
      REPORT_MAIL_TO: ${MAIL_TO}
      # AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      # переменные для dbt
      DBT_PROFILES_DIR: /opt/airflow/currency_dbt
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./src:/opt/airflow/src
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./currency_dbt:/opt/airflow/currency_dbt
      - ./airflow/reports:/opt/airflow/reports/
    command: >
      bash -c "cd /opt/airflow/currency_dbt && dbt deps &&
      airflow scheduler
      "
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: cur_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: cur_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  currency_pgdata:
  grafana_data:
