slice_name: "\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E \u0432\u0430\u043B\
  \u044E\u0442"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 2__table
  viz_type: big_number_total
  slice_id: 33
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: "\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E \u0432\u0430\u043B\
      \u044E\u0442"
    optionName: metric_a8uslimye5r_jiu2nqi1rfs
    sqlExpression: "MAX(\n CASE\n  WHEN dt = CURRENT_DATE\n  THEN currency_cnt\n \
      \ ELSE NULL\n END\n)"
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ybx5tvidqbr_rnt6aw7vfu
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: dt
  subheader: '   '
  header_font_size: 0.6
  subheader_font_size: 0.125
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting:
  - colorScheme: '#ACE1C4'
    column: "\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E \u0432\u0430\u043B\
      \u044E\u0442"
    operator: '='
    targetValue: 54
  - colorScheme: '#EFA1AA'
    column: "\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E \u0432\u0430\u043B\
      \u044E\u0442"
    operator: "\u2260"
    targetValue: 54
  extra_form_data: {}
  dashboards:
  - 3
query_context: "{\"datasource\":{\"id\":2,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"filters\":[{\"col\":\"dt\",\"op\":\"TEMPORAL_RANGE\",\"val\":\"No filter\"\
  }],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\":{},\"columns\"\
  :[],\"metrics\":[{\"aggregate\":null,\"column\":null,\"datasourceWarning\":false,\"\
  expressionType\":\"SQL\",\"hasCustomLabel\":true,\"label\":\"\u0417\u0430\u0433\u0440\
  \u0443\u0436\u0435\u043D\u043E \u0432\u0430\u043B\u044E\u0442\",\"optionName\":\"\
  metric_a8uslimye5r_jiu2nqi1rfs\",\"sqlExpression\":\"MAX(\\n CASE\\n  WHEN dt =\
  \ CURRENT_DATE\\n  THEN currency_cnt\\n  ELSE NULL\\n END\\n)\"}],\"annotation_layers\"\
  :[],\"series_limit\":0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"\
  custom_form_data\":{}}],\"form_data\":{\"datasource\":\"2__table\",\"viz_type\"\
  :\"big_number_total\",\"slice_id\":33,\"metric\":{\"aggregate\":null,\"column\"\
  :null,\"datasourceWarning\":false,\"expressionType\":\"SQL\",\"hasCustomLabel\"\
  :true,\"label\":\"\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043D\u043E \u0432\u0430\
  \u043B\u044E\u0442\",\"optionName\":\"metric_a8uslimye5r_jiu2nqi1rfs\",\"sqlExpression\"\
  :\"MAX(\\n CASE\\n  WHEN dt = CURRENT_DATE\\n  THEN currency_cnt\\n  ELSE NULL\\\
  n END\\n)\"},\"adhoc_filters\":[{\"clause\":\"WHERE\",\"comparator\":\"No filter\"\
  ,\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"filterOptionName\"\
  :\"filter_ybx5tvidqbr_rnt6aw7vfu\",\"isExtra\":false,\"isNew\":false,\"operator\"\
  :\"TEMPORAL_RANGE\",\"operatorId\":\"TEMPORAL_RANGE\",\"sqlExpression\":null,\"\
  subject\":\"dt\"}],\"subheader\":\"   \",\"header_font_size\":0.6,\"subheader_font_size\"\
  :0.125,\"y_axis_format\":\"SMART_NUMBER\",\"time_format\":\"smart_date\",\"conditional_formatting\"\
  :[{\"colorScheme\":\"#ACE1C4\",\"column\":\"\u0417\u0430\u0433\u0440\u0443\u0436\
  \u0435\u043D\u043E \u0432\u0430\u043B\u044E\u0442\",\"operator\":\"=\",\"targetValue\"\
  :54},{\"colorScheme\":\"#EFA1AA\",\"column\":\"\u0417\u0430\u0433\u0440\u0443\u0436\
  \u0435\u043D\u043E \u0432\u0430\u043B\u044E\u0442\",\"operator\":\"\u2260\",\"targetValue\"\
  :54}],\"extra_form_data\":{},\"dashboards\":[3],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: 06c4aade-e495-494c-9601-a0b25ea6cc5b
version: 1.0.0
dataset_uuid: 29aedddb-8366-4b45-8c98-8cb454bf7c44
