slice_name: "\u041F\u0440\u043E\u043F\u0443\u0449\u0435\u043D\u043D\u044B\u0435 \u0437\
  \u0430\u0433\u0440\u0443\u0437\u043A\u0438"
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  viz_type: table
  query_mode: raw
  groupby: []
  temporal_columns_lookup:
    calenda: true
  all_columns:
  - calenda
  - day_type
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_6nrjtk7woc_x7lpx1ehie
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: calenda
  - clause: WHERE
    comparator:
    - true
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_rqhc6nmokqi_1vzfp7ebb8f
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: is_missed
  order_by_cols:
  - '["calenda", false]'
  row_limit: 1000
  table_timestamp_format: '%d/%m/%Y'
  page_length: 10
  allow_render_html: true
  show_cell_bars: false
  align_pn: false
  color_pn: false
  comparison_color_scheme: Green
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[{"col":"calenda","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"is_missed","op":"IN","val":[true]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["calenda","day_type"],"orderby":[["calenda",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"2__table","viz_type":"table","slice_id":3,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{"calenda":true},"all_columns":["calenda","day_type"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_6nrjtk7woc_x7lpx1ehie","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"calenda"},{"clause":"WHERE","comparator":[true],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_rqhc6nmokqi_1vzfp7ebb8f","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"is_missed"}],"order_by_cols":["[\"calenda\",
  false]"],"row_limit":1000,"table_timestamp_format":"%d/%m/%Y","page_length":10,"allow_render_html":true,"show_cell_bars":false,"align_pn":false,"color_pn":false,"comparison_color_scheme":"Green","conditional_formatting":[],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 3d154627-bf52-4301-968b-105373547168
version: 1.0.0
dataset_uuid: 1e720447-c1cd-442e-b9db-1118ef62302b
