apiVersion: 1
contactPoints:
    - orgId: 1
      name: email_alert
      receivers:
        - uid: efszcu6ywwm4ge
          type: email
          settings:
            addresses: recipient_login@example.com
            singleEmail: false
          disableResolveMessage: false
